import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Tclone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/bird.png" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a href="https://nextjs.org">Tclone</a>
        </h1>
        <nav>
          <Link href="/timeline">timeline</Link>
        </nav>
      </main>
    </div>
  );
}
